export const biharConstituencies = [
  {
    district: "Paschim Champaran",
    constituencies: [
      { name: "Valmiki Nagar", code: "1" },
      { name: "Ramnagar (SC)", code: "2" },
      { name: "Narkatiaganj", code: "3" },
      { name: "Bagaha", code: "4" },
      { name: "Lauriya", code: "5" },
      { name: "Nautan", code: "6" },
      { name: "Chanpatia", code: "7" },
      { name: "Bettiah", code: "8" },
      { name: "Sikta", code: "9" },
    ],
  },
  {
    district: "Purvi Champaran",
    constituencies: [
      { name: "Raxaul", code: "10" },
      { name: "Sugauli", code: "11" },
      { name: "Narkatia", code: "12" },
      { name: "Harsidhi (SC)", code: "13" },
      { name: "Govindganj", code: "14" },
      { name: "Kesaria", code: "15" },
      { name: "Kalyanpur", code: "16" },
      { name: "Pipra", code: "17" },
      { name: "Madhuban", code: "18" },
      { name: "Motihari", code: "19" },
      { name: "Chiraia", code: "20" },
      { name: "Dhaka", code: "21" },
    ],
  },
  {
    district: "Sheohar",
    constituencies: [{ name: "Sheohar", code: "22" }],
  },
  {
    district: "Sitamarhi",
    constituencies: [
      { name: "Riga", code: "23" },
      { name: "Bathnaha (SC)", code: "24" },
      { name: "Parihar", code: "25" },
      { name: "Sursand", code: "26" },
      { name: "Bajpatti", code: "27" },
      { name: "Sitamarhi", code: "28" },
      { name: "Runnisaidpur", code: "29" },
      { name: "Belsand", code: "30" },
    ],
  },
  {
    district: "Madhubani",
    constituencies: [
      { name: "Harlakhi", code: "31" },
      { name: "Benipatti", code: "32" },
      { name: "Khajauli", code: "33" },
      { name: "Babubarhi", code: "34" },
      { name: "Bisfi", code: "35" },
      { name: "Madhubani", code: "36" },
      { name: "Rajnagar (SC)", code: "37" },
      { name: "Jhanjharpur", code: "38" },
      { name: "Phulparas", code: "39" },
      { name: "Laukaha", code: "40" },
    ],
  },
  {
    district: "Supaul",
    constituencies: [
      { name: "Nirmali", code: "41" },
      { name: "Pipra", code: "42" },
      { name: "Supaul", code: "43" },
      { name: "Triveniganj (SC)", code: "44" },
      { name: "Chhatapur", code: "45" },
    ],
  },
  {
    district: "Araria",
    constituencies: [
      { name: "Narpatganj", code: "46" },
      { name: "Raniganj (SC)", code: "47" },
      { name: "Forbesganj", code: "48" },
      { name: "Araria", code: "49" },
      { name: "Jokihat", code: "50" },
      { name: "Sikti", code: "51" },
    ],
  },
  {
    district: "Kishanganj",
    constituencies: [
      { name: "Bahadurganj", code: "52" },
      { name: "Thakurganj", code: "53" },
      { name: "Kishanganj", code: "54" },
      { name: "Kochadhaman", code: "55" },
    ],
  },
  {
    district: "Purnia",
    constituencies: [
      { name: "Amour", code: "56" },
      { name: "Baisi", code: "57" },
      { name: "Kasba", code: "58" },
      { name: "Banmankhi (SC)", code: "59" },
      { name: "Rupauli", code: "60" },
      { name: "Dhamdaha", code: "61" },
      { name: "Purnia", code: "62" },
    ],
  },
  {
    district: "Katihar",
    constituencies: [
      { name: "Katihar", code: "63" },
      { name: "Kadwa", code: "64" },
      { name: "Balrampur", code: "65" },
      { name: "Pranpur", code: "66" },
      { name: "Manihari (ST)", code: "67" },
      { name: "Barari", code: "68" },
      { name: "Korha (SC)", code: "69" },
    ],
  },
  {
    district: "Madhepura",
    constituencies: [
      { name: "Alamnagar", code: "70" },
      { name: "Bihariganj", code: "71" },
      { name: "Singheshwar (SC)", code: "72" },
      { name: "Madhepura", code: "73" },
    ],
  },
  {
    district: "Saharsa",
    constituencies: [
      { name: "Sonbarsha (SC)", code: "74" },
      { name: "Saharsa", code: "75" },
      { name: "Simri Bakhtiarpur", code: "76" },
      { name: "Mahishi", code: "77" },
    ],
  },
  {
    district: "Darbhanga",
    constituencies: [
      { name: "Kusheshwar Asthan (SC)", code: "78" },
      { name: "Gaura Bauram", code: "79" },
      { name: "Benipur", code: "80" },
      { name: "Alinagar", code: "81" },
      { name: "Darbhanga Rural", code: "82" },
      { name: "Darbhanga", code: "83" },
      { name: "Hayaghat", code: "84" },
      { name: "Bahadurpur", code: "85" },
      { name: "Keoti", code: "86" },
      { name: "Jale", code: "87" },
    ],
  },
  {
    district: "Muzaffarpur",
    constituencies: [
      { name: "Gaighat", code: "88" },
      { name: "Aurai", code: "89" },
      { name: "Minapur", code: "90" },
      { name: "Bochaha (SC)", code: "91" },
      { name: "Sakra (SC)", code: "92" },
      { name: "Kurhani", code: "93" },
      { name: "Muzaffarpur", code: "94" },
      { name: "Kanti", code: "95" },
      { name: "Baruraj", code: "96" },
      { name: "Paroo", code: "97" },
      { name: "Sahebganj", code: "98" },
    ],
  },
  {
    district: "Gopalganj",
    constituencies: [
      { name: "Baikunthpur", code: "99" },
      { name: "Barauli", code: "100" },
      { name: "Gopalganj", code: "101" },
      { name: "Kuchaikote", code: "102" },
      { name: "Bhorey (SC)", code: "103" },
      { name: "Hathua", code: "104" },
    ],
  },
  {
    district: "Siwan",
    constituencies: [
      { name: "Siwan", code: "105" },
      { name: "Ziradei", code: "106" },
      { name: "Darauli (SC)", code: "107" },
      { name: "Raghunathpur", code: "108" },
      { name: "Daraundha", code: "109" },
      { name: "Barharia", code: "110" },
      { name: "Goriakothi", code: "111" },
      { name: "Maharajganj", code: "112" },
    ],
  },
  {
    district: "Saran",
    constituencies: [
      { name: "Ekma", code: "113" },
      { name: "Manjhi", code: "114" },
      { name: "Baniapur", code: "115" },
      { name: "Taraiya", code: "116" },
      { name: "Marhaura", code: "117" },
      { name: "Chapra", code: "118" },
      { name: "Garkha (SC)", code: "119" },
      { name: "Amnour", code: "120" },
      { name: "Parsa", code: "121" },
      { name: "Sonepur", code: "122" },
    ],
  },
  {
    district: "Vaishali",
    constituencies: [
      { name: "Hajipur", code: "123" },
      { name: "Lalganj", code: "124" },
      { name: "Vaishali", code: "125" },
      { name: "Mahua", code: "126" },
      { name: "Raja Pakar (SC)", code: "127" },
      { name: "Raghopur", code: "128" },
      { name: "Mahnar", code: "129" },
      { name: "Patepur (SC)", code: "130" },
    ],
  },
  {
    district: "Samastipur",
    constituencies: [
      { name: "Kalyanpur (SC)", code: "131" },
      { name: "Warisnagar", code: "132" },
      { name: "Samastipur", code: "133" },
      { name: "Ujiarpur", code: "134" },
      { name: "Morwa", code: "135" },
      { name: "Sarairanjan", code: "136" },
      { name: "Mohiuddinnagar", code: "137" },
      { name: "Bibhutipur", code: "138" },
      { name: "Rosera (SC)", code: "139" },
      { name: "Hasanpur", code: "140" },
    ],
  },
  {
    district: "Begusarai",
    constituencies: [
      { name: "Cheria Bariarpur", code: "141" },
      { name: "Bachhwara", code: "142" },
      { name: "Teghra", code: "143" },
      { name: "Matihani", code: "144" },
      { name: "Sahebpur Kamal", code: "145" },
      { name: "Begusarai", code: "146" },
      { name: "Bakhri (SC)", code: "147" },
    ],
  },
  {
    district: "Khagaria",
    constituencies: [
      { name: "Alauli (SC)", code: "148" },
      { name: "Khagaria", code: "149" },
      { name: "Beldaur", code: "150" },
      { name: "Parbatta", code: "151" },
    ],
  },
  {
    district: "Bhagalpur",
    constituencies: [
      { name: "Bihpur", code: "152" },
      { name: "Gopalpur", code: "153" },
      { name: "Pirpainti (SC)", code: "154" },
      { name: "Kahalgaon", code: "155" },
      { name: "Bhagalpur", code: "156" },
      { name: "Sultanganj", code: "157" },
      { name: "Nathnagar", code: "158" },
    ],
  },
  {
    district: "Banka",
    constituencies: [
      { name: "Amarpur", code: "159" },
      { name: "Dhauraiya (SC)", code: "160" },
      { name: "Banka", code: "161" },
      { name: "Katoria (ST)", code: "162" },
      { name: "Belhar", code: "163" },
    ],
  },
  {
    district: "Munger",
    constituencies: [
      { name: "Tarapur", code: "164" },
      { name: "Munger", code: "165" },
      { name: "Jamalpur", code: "166" },
    ],
  },
  {
    district: "Lakhisarai",
    constituencies: [
      { name: "Suryagarha", code: "167" },
      { name: "Lakhisarai", code: "168" },
    ],
  },
  {
    district: "Sheikhpura",
    constituencies: [
      { name: "Sheikhpura", code: "169" },
      { name: "Barbigha", code: "170" },
    ],
  },
  {
    district: "Nalanda",
    constituencies: [
      { name: "Asthawan", code: "171" },
      { name: "Biharsharif", code: "172" },
      { name: "Rajgir (SC)", code: "173" },
      { name: "Islampur", code: "174" },
      { name: "Hilsa", code: "175" },
      { name: "Nalanda", code: "176" },
      { name: "Harnaut", code: "177" },
    ],
  },
  {
    district: "Patna",
    constituencies: [
      { name: "Mokama", code: "178" },
      { name: "Barh", code: "179" },
      { name: "Bakhtiarpur", code: "180" },
      { name: "Digha", code: "181" },
      { name: "Bankipur", code: "182" },
      { name: "Kumhrar", code: "183" },
      { name: "Patna Sahib", code: "184" },
      { name: "Fatuha", code: "185" },
      { name: "Danapur", code: "186" },
      { name: "Maner", code: "187" },
      { name: "Phulwari (SC)", code: "188" },
      { name: "Masaurhi (SC)", code: "189" },
      { name: "Paliganj", code: "190" },
      { name: "Bikram", code: "191" },
    ],
  },
  {
    district: "Bhojpur",
    constituencies: [
      { name: "Sandesh", code: "192" },
      { name: "Barhara", code: "193" },
      { name: "Arrah", code: "194" },
      { name: "Agiaon (SC)", code: "195" },
      { name: "Tarari", code: "196" },
      { name: "Jagdishpur", code: "197" },
    ],
  },
  {
    district: "Buxar",
    constituencies: [
      { name: "Shahpur", code: "198" },
      { name: "Brahampur", code: "199" },
      { name: "Buxar", code: "200" },
      { name: "Dumraon", code: "201" },
    ],
  },
  {
    district: "Kaimur",
    constituencies: [
      { name: "Rajpur (SC)", code: "202" },
      { name: "Ramgarh", code: "203" },
      { name: "Mohania (SC)", code: "204" },
      { name: "Bhabua", code: "205" },
      { name: "Chainpur", code: "206" },
    ],
  },
  {
    district: "Rohtas",
    constituencies: [
      { name: "Chenari (SC)", code: "207" },
      { name: "Sasaram", code: "208" },
      { name: "Kargahar", code: "209" },
      { name: "Dinara", code: "210" },
      { name: "Nokha", code: "211" },
      { name: "Dehri", code: "212" },
      { name: "Karakat", code: "213" },
    ],
  },
  {
    district: "Arwal",
    constituencies: [
      { name: "Arwal", code: "214" },
      { name: "Kurtha", code: "215" },
    ],
  },
  {
    district: "Jehanabad",
    constituencies: [
      { name: "Jehanabad", code: "216" },
      { name: "Ghosi", code: "217" },
      { name: "Makhdumpur (SC)", code: "218" },
    ],
  },
  {
    district: "Aurangabad",
    constituencies: [
      { name: "Goh", code: "219" },
      { name: "Obra", code: "220" },
      { name: "Nabinagar", code: "221" },
      { name: "Kutumba (SC)", code: "222" },
      { name: "Aurangabad", code: "223" },
      { name: "Rafiganj", code: "224" },
    ],
  },
  {
    district: "Gaya",
    constituencies: [
      { name: "Gurua", code: "225" },
      { name: "Sherghati", code: "226" },
      { name: "Imamganj (SC)", code: "227" },
      { name: "Barachatti (SC)", code: "228" },
      { name: "Bodh Gaya (SC)", code: "229" },
      { name: "Gaya Town", code: "230" },
      { name: "Tikari", code: "231" },
      { name: "Belaganj", code: "232" },
      { name: "Atri", code: "233" },
      { name: "Wazirganj", code: "234" },
    ],
  },
  {
    district: "Nawada",
    constituencies: [
      { name: "Rajauli (SC)", code: "235" },
      { name: "Hisua", code: "236" },
      { name: "Nawada", code: "237" },
      { name: "Gobindpur", code: "238" },
      { name: "Warsaliganj", code: "239" },
    ],
  },
  {
    district: "Jamui",
    constituencies: [
      { name: "Sikandra (SC)", code: "240" },
      { name: "Jamui", code: "241" },
      { name: "Jhajha", code: "242" },
      { name: "Chakai", code: "243" },
    ],
  },
];
